// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.ClassesManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181219003016_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.ClassesManagement.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AuthorId");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasMaxLength(35);

                    b.Property<DateTime?>("DeletedDate")
                        .HasMaxLength(7);

                    b.Property<Guid>("EntityId");

                    b.Property<DateTime>("LastChangeDate")
                        .HasMaxLength(7);

                    b.Property<int>("Semester")
                        .HasMaxLength(2);

                    b.Property<int>("Year")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Entities.ClassesManagement.Laboratory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AuthorId");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasMaxLength(35);

                    b.Property<DateTime?>("DeletedDate")
                        .HasMaxLength(7);

                    b.Property<Guid>("EntityId");

                    b.Property<DateTime>("LastChangeDate")
                        .HasMaxLength(7);

                    b.Property<int>("Semester")
                        .HasMaxLength(2);

                    b.Property<int>("Year")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.ToTable("Laboratories");
                });
#pragma warning restore 612, 618
        }
    }
}
